name: app
type: 'php:8.1'
mounts:
  'web/uploads':
    source: local
    source_path: uploads
disk: 2048
hooks:
  build: |
    set -e
  deploy: |
    set -e
web:
  locations:
    '/':
      root: "web"
      passthru: "/index.php"